project_id = "yvczrgulhswbxsfnyqan"

[functions.ai-analyze]
verify_jwt = true

[functions.ai-chat-interview]
verify_jwt = false

[functions.ai-chat-simulation]
verify_jwt = false

[functions.ai-sales-simulation]
verify_jwt = false

[functions.ai-generate-document]
verify_jwt = true

[functions.ai-generate-job-content]
verify_jwt = true

[functions.ai-generate-workflow]
verify_jwt = true

[functions.google-calendar]
verify_jwt = true
