project_id = "yvczrgulhswbxsfnyqan"

[functions.ai-analyze]
verify_jwt = true

[functions.ai-generate-document]
verify_jwt = true

[functions.ai-generate-job-content]
verify_jwt = true

[functions.ai-generate-workflow]
verify_jwt = true

[functions.google-calendar]
verify_jwt = true
